---
- name: Update packages
  apt:
    update_cache: yes

- name: Install pip2
  apt:
    name: python-pip
    state: present

- name: Install docker-py
  become: true
  pip:
    name: docker-py
    state: present

- name: Ensure docker is started
  service:
    name: docker
    state: started